language: node_js
node_js: 
    - 12
install: npm install
script: npm test
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 
    - npm run coverage
    - npm run coveralls
